# Generated by Django 5.1.4 on 2025-01-29 10:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platelt',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='platelt',
            name='plate_number',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
